-- OAuth broker schema for ADVNCD CLI login flow.
-- Apply in Supabase SQL editor or via Supabase CLI migrations.

create extension if not exists pgcrypto;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'cli_login_status') then
    create type cli_login_status as enum ('pending', 'approved', 'denied', 'expired');
  end if;
end $$;

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  google_sub text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cli_login_sessions (
  id bigint generated by default as identity primary key,
  session_id text not null unique,
  status cli_login_status not null default 'pending',
  device_name text,
  user_id uuid references public.users(id) on delete set null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  denied_at timestamptz,
  oauth_state_hash text,
  oauth_nonce text,
  oauth_started_at timestamptz,
  poll_count integer not null default 0,
  last_poll_at timestamptz,
  ip inet,
  user_agent text
);

create index if not exists cli_login_sessions_status_expires_idx
  on public.cli_login_sessions(status, expires_at);

create index if not exists cli_login_sessions_user_id_idx
  on public.cli_login_sessions(user_id);

create table if not exists public.oauth_accounts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  provider text not null,
  provider_account_id text,
  encrypted_refresh_token text not null,
  encryption_key_version text not null default 'v1',
  scopes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint oauth_accounts_user_provider_unique unique (user_id, provider)
);

create unique index if not exists oauth_accounts_provider_account_unique
  on public.oauth_accounts(provider, provider_account_id)
  where provider_account_id is not null;

create table if not exists public.app_tokens (
  id bigint generated by default as identity primary key,
  token_id uuid not null default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  session_id text references public.cli_login_sessions(session_id) on delete set null,
  refresh_token_hash text not null unique,
  refresh_expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  last_used_at timestamptz,
  revoked_at timestamptz
);

create index if not exists app_tokens_user_id_idx
  on public.app_tokens(user_id);

create index if not exists app_tokens_active_idx
  on public.app_tokens(refresh_expires_at, revoked_at);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  user_id uuid references public.users(id) on delete set null,
  session_id text,
  actor_ip inet,
  actor_user_agent text,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_events_created_at_idx
  on public.audit_events(created_at desc);

create index if not exists audit_events_event_type_idx
  on public.audit_events(event_type);

alter table public.users enable row level security;
alter table public.cli_login_sessions enable row level security;
alter table public.oauth_accounts enable row level security;
alter table public.app_tokens enable row level security;
alter table public.audit_events enable row level security;

-- Optional trigger helper for updated_at columns.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at
before update on public.users
for each row execute function public.set_updated_at();

drop trigger if exists oauth_accounts_set_updated_at on public.oauth_accounts;
create trigger oauth_accounts_set_updated_at
before update on public.oauth_accounts
for each row execute function public.set_updated_at();
